CONFIG -= app_bundle
CONFIG += console
CONFIG += debug
HEADERS += include/nzmqt/nzmqt.hpp include/prax/*.h
LIBS += -lgd -lzmq -ljson
QT += core webkit network
QMAKE_CXXFLAGS += -fPIC
SOURCES += src/prax.cpp src/prax/*.cpp
INCLUDEPATH += include
TARGET = prax
TEMPLATE = app
